#!/usr/bin/env bash

#set -euxo pipefail

command -v jq >/dev/null 2>&1
jq_result=$?

if [ $jq_result -ne 0 ]; then
  echo "You do not have jq in your path, please install it to continue"
  exit 1
fi

node=$(cat .rdev-configs/configs.json | jq -r '.sname')
cookie=$(cat .rdev-configs/configs.json | jq -r '.cookie')

next=$(ls -1 logs*.log 2> /dev/null | wc -l)

iex --sname $node --cookie $cookie -S mix > logs$next.log 2>&1
